# Generated by Django 4.2.16 on 2024-11-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_user_rassylka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Пациент'), ('doctor', 'Врач'), ('admin', 'Администратор')], default='patient', max_length=10),
        ),
    ]
