# Generated by Django 4.2.16 on 2024-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные'),
        ),
    ]
