# Generated by Django 5.1.6 on 2025-02-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_page_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='extra_data',
        ),
    ]
