# Generated by Django 4.2.16 on 2024-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='wait', max_length=255),
        ),
    ]
