# Generated by Django 4.2.16 on 2024-11-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='usluga',
            field=models.CharField(choices=[('сonsultation', 'Консультация'), ('treatment', 'Лечение'), ('operation', 'Операция')], default='сonsultation', max_length=100),
        ),
    ]
