# Generated by Django 4.2.16 on 2024-11-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_appointment_usluga'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
