# Generated by Django 4.2.16 on 2024-12-26 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0005_feedback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('snils', models.CharField(blank=True, max_length=11, null=True, verbose_name='СНИЛС')),
                ('dms', models.CharField(blank=True, max_length=50, null=True, verbose_name='ДМС')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('passport_date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('passport_issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('passport_photo1', models.ImageField(blank=True, null=True, upload_to='passport_photos/', verbose_name='Фото паспорта 1')),
                ('passport_photo2', models.ImageField(blank=True, null=True, upload_to='passport_photos/', verbose_name='Фото паспорта 2')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.TextField(verbose_name='Вопрос 1')),
                ('question2', models.TextField(verbose_name='Вопрос 2')),
                ('question3', models.TextField(verbose_name='Вопрос 3')),
                ('question4', models.TextField(verbose_name='Вопрос 4')),
                ('question5', models.TextField(verbose_name='Вопрос 5')),
                ('completed', models.BooleanField(default=False, verbose_name='Заполнена')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
