# Generated by Django 4.2.16 on 2024-12-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_userprofile_patientsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='passport_date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия паспорта'),
        ),
    ]
