# Generated by Django 4.2.16 on 2024-12-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_userprofile_passport_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Девушка')], default='male', max_length=10, verbose_name='Пол'),
        ),
    ]
