# Generated by Django 4.2.16 on 2024-12-26 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0008_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsurvey',
            name='question1',
            field=models.TextField(verbose_name='Были у вас когда-либо аллергические реакции'),
        ),
        migrations.AlterField(
            model_name='patientsurvey',
            name='question2',
            field=models.TextField(verbose_name='Есть у вас хронические заболевания'),
        ),
        migrations.AlterField(
            model_name='patientsurvey',
            name='question3',
            field=models.TextField(verbose_name='Страдаете ли заболеваниями полости рта'),
        ),
        migrations.AlterField(
            model_name='patientsurvey',
            name='question4',
            field=models.TextField(verbose_name='Есть в вашей семье аллергические реакции '),
        ),
        migrations.AlterField(
            model_name='patientsurvey',
            name='question5',
            field=models.TextField(verbose_name='Есть ли у вас особенности'),
        ),
        migrations.CreateModel(
            name='MedicalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_series', models.CharField(max_length=4)),
                ('passport_number', models.CharField(max_length=6)),
                ('passport_issued_by', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=512)),
                ('consent_date', models.DateField()),
                ('signature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_consent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
