# Generated by Django 4.2.16 on 2024-12-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_patientsurvey_question1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalconsent',
            name='address',
            field=models.CharField(max_length=512, verbose_name='проживающий по адресу '),
        ),
        migrations.AlterField(
            model_name='medicalconsent',
            name='consent_date',
            field=models.DateField(verbose_name='Дата: '),
        ),
        migrations.AlterField(
            model_name='medicalconsent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicalconsent',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Я, '),
        ),
        migrations.AlterField(
            model_name='medicalconsent',
            name='passport_issued_by',
            field=models.CharField(max_length=255, verbose_name='выдан '),
        ),
        migrations.AlterField(
            model_name='medicalconsent',
            name='passport_number',
            field=models.CharField(max_length=6, verbose_name=' номер :'),
        ),
        migrations.AlterField(
            model_name='medicalconsent',
            name='passport_series',
            field=models.CharField(max_length=4, verbose_name='паспорт: серия:'),
        ),
        migrations.AlterField(
            model_name='medicalconsent',
            name='signature',
            field=models.BooleanField(default=False, verbose_name='Подписать электронной подписью'),
        ),
    ]
