# Generated by Django 4.2.16 on 2024-12-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_medicalconsent_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AlterField(
            model_name='medicalconsent',
            name='consent_date',
            field=models.DateField(verbose_name='Дата '),
        ),
        migrations.AlterField(
            model_name='medicalconsent',
            name='signature',
            field=models.BooleanField(verbose_name='Подписать электронной подписью'),
        ),
    ]
