# Generated by Django 5.1.6 on 2025-02-21 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_ordercall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, default='wait', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalconsent',
            name='consent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата '),
        ),
    ]
