# Generated by Django 5.1.6 on 2025-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_appointment_patient_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalconsent',
            name='signature',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подписать электронной подписью'),
        ),
    ]
